### ISSUE TITLE
Sidebar isn't showing up on website

### ISSUE THREAD

**Issue by uwbankopmaat** [calculoidapp/calculoidapp.github.io#10]
Hi guys,

I've built a calculator on your website including photos in the sidebar which are showing in the editor, however when viewing it on the website, everything is showing up except the sidebar.

I have deleted the site's original sidebar by adding customm css, but even when I erased this code, it didn't show up.

The link to the site is as follows: http://uwbankopmaat.nl/?page_id=175

Hope someone can help me out!

**Comment by escopecz** [comment]
Hello,
we decided today we will drop the sidebar feature. It's archaic feature before the Gridster drag&drop manager and only few calculators actually use it. Now the sidebar can be simply created with HTML field positioned as the right column.
Let me know if that worked for you.
