### ISSUE TITLE
Send Email function doesn't work

### ISSUE THREAD

**Issue by JimWkp** [calculoidapp/calculoidapp.github.io#18]
The Send eMail function was added to our calculator, but doesn't appear on our web page. The function is fine on the Calculoid site, and our membership is up to date. Any suggestions?

**Comment by escopecz** [comment]
Please contact the service support at support@calculoid.com

**Comment by JimWkp** [comment]
Support doesn’t reply.

Emailed nine times since Sept. 8th.

Calculoid publishes Github as a report issues link.

Jim


[cid:image002.jpg@01D25082.A6DC1F20]
