### ISSUE TITLE
Calculators not working

### ISSUE THREAD

**Issue by SaraBurkhard** [calculoidapp/calculoidapp.github.io#19]
Hello, 

My team and I have tried to access a calculator I created. Everyone who's tried has received this page instead. 
![pasted image at 2017_04_25 07_25 am](https://cloud.githubusercontent.com/assets/28001705/25381213/1d6b81e4-29b3-11e7-9593-2a8526194195.png)

Even when I try to log in, it directs me to this page. I'm not sure if this is just an issue on my end, but we've tried on several devices from different browsers and this is all that seems to come up.

I would appreciate your help in solving this, as we've really enjoyed using this calculator. 

Thank you, 
Sara Burkhard

**Comment by sabmakhmudova** [comment]
Yes, we know about this issue, currently trying to repair it.

**Comment by SaraBurkhard** [comment]
Thank you so much! :)

**Comment by sabmakhmudova** [comment]
Repaired. Please test and report if you still having problems.

**Comment by SaraBurkhard** [comment]
Thank you. It seems to be working well again.
