### ISSUE TITLE
calculator changed without editing

### ISSUE THREAD

**Issue by marcomngh** [calculoidapp/calculoidapp.github.io#8]
Hi,
My calculator kWh   since few days ago changed format view by itself and it is now messy and impossible to use, is it possible to restore to how it was?

http://calculoid.com/#/calculator/577

thanks,
Marco

**Comment by escopecz** [comment]
Hi Marco,

thank you for your report. We released new calculator editor which changed field positioning from float based to grid-based. With grid positioning you have more control about where fields are, you can also set field height.

Sadly, these two positioning systems aren't backward compatible. We worked hard to make transition seamless for existing calculators, but some users are having problems like you have. We try to fix all issues and hopefully, we did now.

I modified your calculator. Not sure if it is the same as it was though.
