### ISSUE TITLE
NaN message when fields are empty

### ISSUE THREAD

**Issue by prodos** [calculoidapp/calculoidapp.github.io#9]
I've created a very simple calculator that merely performs the following:

Field A x 1.6 + Field B

http://calculoid.com/#/calculator/1579

When one or both fields are empty I get an error message along the following lines:

0 ... Formula before evaluation: "NaN * 1.6 + NaN". Error: undefined variable: NaN

Question: Is it possible to avoid this error message when the fields are empty?

Meanwhile I've simply entered "0" in each field as default values.

Thanks for any suggestions.

Best Wishes,

PRODOS
Melbourne, Australia

**Comment by escopecz** [comment]
That's a great question. I left it like that so calculator owners will be forced to insert default values. All I can do is to replace empty value with a number. The best number to replace an empty field would be zero probably. But then consider this formula:

```
Field A x 1.6 / Field B
```

In this case, if Field B is empty=zero, then the result is mathematically undefined. But replacing empty values for zeroes makes more sense. I'll implement it. If you would have a better idea, let me know.

**Comment by prodos** [comment]
Greetings.

Thanks for getting back to me and for the offer to make blank fields not show an error message.

Much appreciated. :-)

Best Wishes,

PRODOS
Melbourne, Australia

**Comment by prodos** [comment]
Greetings.

Thanks for getting back to me and for the offer to make blank fields not show an error message.

Much appreciated. :-)

Best Wishes,

PRODOS
Melbourne, Australia

**Comment by prodos** [comment]
Greetings.

Thanks for getting back to me and for the offer to make blank fields not show an error message.

Much appreciated. :-)

Best Wishes,

PRODOS
Melbourne, Australia

**Comment by prodos** [comment]
Greetings.Thanks for getting back to me and for the offer to make blank fields not show an error message.Much appreciated. :-)Best Wishes,PRODOSMelbourne, Australia


-------- Original Message --------
Subject: Re: [calculoidapp.github.io] NaN message when fields are empty
(#9)

**Comment by prodos** [comment]
Oh darn! 

Sorry about the multiple copies. I clicked the green "Comment" button but it didn't seem to work, so I kept clicking it.

Apologies.

**Comment by escopecz** [comment]
The change was deployed. Thanks for suggestion!

**Comment by prodos** [comment]
Many thanks! :-)
